apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/coolapp/devfile-sample-python-basic@sha256:775d2ddaf3482485065b18c2fa2c5995805e1d789ac6572e8bf01a71716bde6a
        name: my-python
        resources: {}
status: {}
