apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/coolapp/devfile-sample-python-basic@sha256:9aa1b14c49c2c22972a1b808141a03eac28f7a56369cef8f69d2a6e3dade458a
        name: my-python
        resources: {}
status: {}
